name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    uses: banua-coder/banua-coder-workflow/.github/workflows/ci-go.yml@main
    with:
      go-version: "1.26.x"
      build-target: ./cmd/main.go
      build-output: pico-api-go
      coverage-threshold: 80
      post-coverage-comment: true
      golangci-lint-version: v2.10.1
      test-packages: "./internal/... ./pkg/utils/..."
