name: Release Workflow

on:
  pull_request:
    branches: [main]
    types: [closed]
  push:
    branches:
      - "release/**"
      - "hotfix/**"

jobs:
  release:
    uses: banua-coder/banua-coder-workflow/.github/workflows/release.yml@v1
    with:
      project-type: web-app
      main-branch: main
      develop-branch: develop
    secrets:
      GH_PAT: ${{ secrets.WORKFLOW_PAT }}
